<?php

/**
 * Implementation of hook_strongarm().
 */
function ori_regform_tooltips_feature_strongarm() {
  $export = array();

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltipcount';
  $strongarm->value = '3';
  $export['ori_regform_tooltipcount'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink1';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink1'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink10';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink10'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink2';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink2'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink3';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink3'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink4';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink4'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink5';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink5'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink6';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink6'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink7';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink7'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink8';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink8'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiplink9';
  $strongarm->value = '';
  $export['ori_regform_tooltiplink9'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext1';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext1'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext10';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext10'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext2';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext2'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext3';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext3'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext4';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext4'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext5';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext5'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext6';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext6'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext7';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext7'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext8';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext8'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltiptext9';
  $strongarm->value = '';
  $export['ori_regform_tooltiptext9'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_count';
  $strongarm->value = '15';
  $export['ori_regform_tooltip_count'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group1';
  $strongarm->value = 'important';
  $export['ori_regform_tooltip_group1'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group10';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group10'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group11';
  $strongarm->value = 'important';
  $export['ori_regform_tooltip_group11'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group12';
  $strongarm->value = 'important';
  $export['ori_regform_tooltip_group12'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group13';
  $strongarm->value = 'important';
  $export['ori_regform_tooltip_group13'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group14';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group14'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group15';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group15'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group2';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group2'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group3';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group3'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group4';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group4'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group5';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group5'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group6';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group6'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group7';
  $strongarm->value = '';
  $export['ori_regform_tooltip_group7'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group8';
  $strongarm->value = 'important';
  $export['ori_regform_tooltip_group8'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_group9';
  $strongarm->value = 'important';
  $export['ori_regform_tooltip_group9'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_groups';
  $strongarm->value = array(
    '' => 'Нет',
    'important' => 'important block',
  );
  $export['ori_regform_tooltip_groups'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link1';
  $strongarm->value = 'Не получилось заполнить регформу?';
  $export['ori_regform_tooltip_link1'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link10';
  $strongarm->value = '';
  $export['ori_regform_tooltip_link10'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link11';
  $strongarm->value = 'Сколько стоит регистрация?';
  $export['ori_regform_tooltip_link11'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link12';
  $strongarm->value = 'Что произойдет после регистрации?';
  $export['ori_regform_tooltip_link12'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link13';
  $strongarm->value = 'Как удалить свой номер консультанта?';
  $export['ori_regform_tooltip_link13'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link14';
  $strongarm->value = '';
  $export['ori_regform_tooltip_link14'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link15';
  $strongarm->value = '';
  $export['ori_regform_tooltip_link15'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link2';
  $strongarm->value = '';
  $export['ori_regform_tooltip_link2'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link3';
  $strongarm->value = 'прочтите это важно';
  $export['ori_regform_tooltip_link3'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link4';
  $strongarm->value = '<span class="tip-field"></span>';
  $export['ori_regform_tooltip_link4'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link5';
  $strongarm->value = '<span class="tip-field"></span>';
  $export['ori_regform_tooltip_link5'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link6';
  $strongarm->value = 'Мне не пришло письмо';
  $export['ori_regform_tooltip_link6'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link7';
  $strongarm->value = 'сначала введите индекс';
  $export['ori_regform_tooltip_link7'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link8';
  $strongarm->value = 'Политика конфиденциальности';
  $export['ori_regform_tooltip_link8'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_link9';
  $strongarm->value = 'Зачем регистрироваться в Oriflame?';
  $export['ori_regform_tooltip_link9'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text1';
  $strongarm->value = 'Если по каким либо причинам у вас не получилось заполнить регистрационную форму, тогда войдите в раздел "Контакты" на моем сайте и напишите мне следующее сообщение и ваш мобильный телефон: "Не могу заполнить регистрационную форму, тел. 8 -999 - 111 11 11" - я перезвоню вам в ближайшее время и приму вашу регистрацию по телефону.';
  $export['ori_regform_tooltip_text1'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text10';
  $strongarm->value = '';
  $export['ori_regform_tooltip_text10'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text11';
  $strongarm->value = 'Регистрация на нашем сайте бесплатна, хотя сама в регистрация в Oriflame стоит 149 рублей (кроме льготных регистрации, на непродолжительное время, при которых цена на регистрацию уменьшается), и вносится один раз в год. Плата за регистрацию будет добавлена в ваш первый заказ. Если вы не сделаете ни одного заказа, то стоимость регистрации оплачивать не нужно.';
  $export['ori_regform_tooltip_text11'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text12';
  $strongarm->value = 'После регистрации (как правило в течении 15 минут) на Ваш e-mail будет отправлена информация о вашем регистрационном номере и пароле для входа на официальный сайт <a href="http://www.oriflame.ru">www.oriflame.ru</a> и подробная инструкция о том, как оформить свой первый заказ на сайте <a href="http://www.oriflame.ru">www.oriflame.ru</a>, как его оплатить и где получить.';
  $export['ori_regform_tooltip_text12'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text13';
  $strongarm->value = 'Если в течении 12 месяцев с момента регистрации, вы не сделаете ни одного заказа, то ваш регистрационный номер удалится автоматически, и для того что бы сделать заказ в качестве консультанта компании, вам нужно будет вновь зарегистрироваться за 149 рублей.';
  $export['ori_regform_tooltip_text13'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text14';
  $strongarm->value = '';
  $export['ori_regform_tooltip_text14'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text15';
  $strongarm->value = '';
  $export['ori_regform_tooltip_text15'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text2';
  $strongarm->value = '';
  $export['ori_regform_tooltip_text2'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text3';
  $strongarm->value = 'Пожалуйста будьте очень внимательны при указании вашего e-mail. Если вы неверно укажите свой e-mail, мы не сможем выслать вам инструкцию по оформлению заказов!';
  $export['ori_regform_tooltip_text3'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text4';
  $strongarm->value = 'Например, если ваш номер  <br>
+7 <b class="green">903</b> 138-41-11, <br>
то префикс будет <b class="green">903</b> ';
  $export['ori_regform_tooltip_text4'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text5';
  $strongarm->value = 'Например, если ваш номер  <br>
+7 903 <b class="green">138-41-11</b>, <br>
то номер телефона будет <b class="green">138-41-11</b> ';
  $export['ori_regform_tooltip_text5'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text6';
  $strongarm->value = 'Проверьте папку "Спам", если письма нет и там, то ничего не предпринимайте, повторно заполнять анкету не нужно. Мы сами перезвоним вам на номера телефонов указанных вами при регистрации в течении 1 часа.';
  $export['ori_regform_tooltip_text6'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text7';
  $strongarm->value = 'Ввод места проживания, автоматизирован. Сначала введите индекс!';
  $export['ori_regform_tooltip_text7'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text8';
  $strongarm->value = '1. Вся личная информация введенная вами в этой форме, будет использована только для внесения в базу данных компании Oriflame, для присвоения Вам номера консультанта или клиента Oriflame и не будет использована в каких либо других целях.

    Персональные данные указанные в п.1, вы передаете нам на неограниченный срок хранения, с возможностью удаления по вашему запросу в любой момент. Запрос на удаление будет выполнен в течении суток.';
  $export['ori_regform_tooltip_text8'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_text9';
  $strongarm->value = 'Зарегистрировавшись в Орифлейм в качестве консультанта компании, вы получаете возможность покупки косметики Oriflame для себя и своей семьи по дистрибьюторским ценам (ДЦ) компании со скидкой 23% от цены каталога, и конечно же, возможность зарабатывать на продаже косметики, и построении бизнеса с Oriflame. Также у вас появится возможность получать отличные подарки выполняя условия специальных акций Oriflame.';
  $export['ori_regform_tooltip_text9'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title1';
  $strongarm->value = 'Как заполнить регформу';
  $export['ori_regform_tooltip_title1'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title10';
  $strongarm->value = '';
  $export['ori_regform_tooltip_title10'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title11';
  $strongarm->value = 'Сколько стоит регистрация?';
  $export['ori_regform_tooltip_title11'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title12';
  $strongarm->value = 'Что произойдет после регистрации?';
  $export['ori_regform_tooltip_title12'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title13';
  $strongarm->value = 'Как удалить свой номер консультанта?';
  $export['ori_regform_tooltip_title13'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title14';
  $strongarm->value = '';
  $export['ori_regform_tooltip_title14'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title15';
  $strongarm->value = '';
  $export['ori_regform_tooltip_title15'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title2';
  $strongarm->value = '';
  $export['ori_regform_tooltip_title2'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title3';
  $strongarm->value = 'прочтите это важно';
  $export['ori_regform_tooltip_title3'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title4';
  $strongarm->value = 'Что такое префикс?';
  $export['ori_regform_tooltip_title4'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title5';
  $strongarm->value = 'Номер мобильного телефона';
  $export['ori_regform_tooltip_title5'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title6';
  $strongarm->value = 'Мне не пришло письмо';
  $export['ori_regform_tooltip_title6'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title7';
  $strongarm->value = 'сначала введите индекс';
  $export['ori_regform_tooltip_title7'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title8';
  $strongarm->value = 'Политика конфиденциальности';
  $export['ori_regform_tooltip_title8'] = $strongarm;

  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'ori_regform_tooltip_title9';
  $strongarm->value = 'Зачем регистрироваться в Oriflame?';
  $export['ori_regform_tooltip_title9'] = $strongarm;

  return $export;
}
