/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
 **/


(function ($, Drupal, drupalSettings) {
  Drupal.behaviors.extendSettings = {
    attach: function attach(context) {
      if (fld = drupalSettings.extendSettings.masked_field) {
        var input = 'input[type="tel"]';
        if (!$(input).hasClass('masked')) {
          $(input).removeClass('masked').addClass('masked').mask("+7-9999999999");
        }
      }
    }
  }
})(jQuery, Drupal, drupalSettings);
